name: lasercare
description: "lasercare"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  firebase_core: ^3.6.0
  http: ^1.2.2
  provider: ^6.1.2
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
 
  assets:
      - assets/icons/curativo.png 
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg